# -*- coding: utf-8 -*-
"""Toxic_Comment_Detection_LSTM_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XMVCeL6FIYQ5lzqZoOP4SWJDFPx2dVny
"""

!pip install wordcloud -q

import os, re, warnings
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Bidirectional
from tensorflow.keras.callbacks import EarlyStopping

nltk.download("stopwords", quiet=True)

csv_file_path = "toxic_comments.csv"

df = pd.read_csv(csv_file_path)

print(f"Dataset loaded — {len(df)} comments ({sum(df.Label=='Toxic')} Toxic, {sum(df.Label=='Non-Toxic')} Non-Toxic)")
df.head(6)

stop_words = set(stopwords.words("english"))
stemmer    = PorterStemmer()

def preprocess(text):
    text   = text.lower()
    tokens = re.findall(r"[a-z]+", text)
    tokens = [t for t in tokens if t not in stop_words]
    tokens = [stemmer.stem(t) for t in tokens]
    return " ".join(tokens)

df["Cleaned"]   = df["Comment"].apply(preprocess)
df["Label_Num"] = (df["Label"] == "Toxic").astype(int)

MAX_WORDS = 2000
MAX_LEN   = 30

tokenizer = Tokenizer(num_words=MAX_WORDS, oov_token="<OOV>")
tokenizer.fit_on_texts(df["Cleaned"])

sequences  = tokenizer.texts_to_sequences(df["Cleaned"])
padded     = pad_sequences(sequences, maxlen=MAX_LEN, padding="post", truncating="post")
vocab_size = len(tokenizer.word_index) + 1

print(f"Vocabulary size    : {vocab_size}")
print(f"Max sequence length: {MAX_LEN}")
print(f"Padded shape       : {padded.shape}")
print()
for _, row in df[["Comment","Cleaned","Label"]].head(4).iterrows():
    print(f"[{row.Label}]  {row.Comment[:40]}  =>  {row.Cleaned}")

X = padded
y = df["Label_Num"].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Training samples : {len(X_train)}")
print(f"Testing  samples : {len(X_test)}")

model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=128, input_length=MAX_LEN),
    Bidirectional(LSTM(64, dropout=0.3, recurrent_dropout=0.3)),
    Dense(32, activation="relu"),
    Dropout(0.4),
    Dense(1, activation="sigmoid"),
])

model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
model.summary()

early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

history = model.fit(
    X_train, y_train,
    epochs=30,
    batch_size=16,
    validation_data=(X_test, y_test),
    callbacks=[early_stopping],
    verbose=1,
)

loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test Accuracy : {accuracy * 100:.2f}%")
print(f"Test Loss     : {loss:.4f}")

y_pred = (model.predict(X_test, verbose=0).flatten() >= 0.5).astype(int)
print()
print(classification_report(y_test, y_pred, target_names=["Non-Toxic", "Toxic"]))

fig, axes = plt.subplots(1, 3, figsize=(16, 4))
epochs_range = range(1, len(history.history['accuracy']) + 1)

axes[0].plot(epochs_range, history.history["accuracy"],     label="Train",      color="#2ecc71", linewidth=2)
axes[0].plot(epochs_range, history.history["val_accuracy"], label="Validation", color="#e74c3c", linewidth=2, linestyle="--")
axes[0].set_title("Accuracy"); axes[0].set_xlabel("Epoch"); axes[0].set_ylabel("Accuracy")
axes[0].legend(); axes[0].grid(True, alpha=0.3)

axes[1].plot(epochs_range, history.history["loss"],     label="Train",      color="#3498db", linewidth=2)
axes[1].plot(epochs_range, history.history["val_loss"], label="Validation", color="#e67e22", linewidth=2, linestyle="--")
axes[1].set_title("Loss"); axes[1].set_xlabel("Epoch"); axes[1].set_ylabel("Loss")
axes[1].legend(); axes[1].grid(True, alpha=0.3)

cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Non-Toxic","Toxic"],
            yticklabels=["Non-Toxic","Toxic"], ax=axes[2])
axes[2].set_title("Confusion Matrix")
axes[2].set_ylabel("True"); axes[2].set_xlabel("Predicted")

plt.tight_layout()
plt.show()

def predict_comment(comment):
    cleaned  = preprocess(comment)
    seq      = tokenizer.texts_to_sequences([cleaned])
    padded_s = pad_sequences(seq, maxlen=MAX_LEN, padding="post", truncating="post")
    prob     = model.predict(padded_s, verbose=0)[0][0]
    label    = "Toxic" if prob >= 0.5 else "Non-Toxic"
    conf     = prob * 100 if label == "Toxic" else (1 - prob) * 100
    return label, conf

test_comments = [
    "I appreciate your effort and hard work",
    "You are a complete idiot and worthless",
    "This is a great learning experience",
    "I hate everything about you",
]

for c in test_comments:
    label, conf = predict_comment(c)
    icon = "TOXIC" if label == "Toxic" else "NON-TOXIC"
    print(f"[{icon}] ({conf:.1f}%)  {c}")

my_comment = "You are so talented and I love your work"

label, conf = predict_comment(my_comment)
print(f"Comment    : {my_comment}")
print(f"Prediction : {label}  ({conf:.1f}% confidence)")